CREATE TABLE IF NOT EXISTS operations (
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    concept text NOT NULL,
    operationdate date NOT NULL,
    amounttype text NOT NULL,
    amount INTEGER NOT NULL
);

INSERT INTO operations (concept, operationdate, amounttype, amount)
    VALUES('LEARN IT', '02-25-2005', 'in', -55000);

INSERT INTO operations (concept, operationdate, amounttype, amount)
    VALUES('Comprar una moto', '12-01-2010', 'in', -45000);

INSERT INTO operations (concept, operationdate, amounttype, amount)
    VALUES('Consegui un trabajo en it', '09-30-2021', 'in', 155000);